
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/ruby:2.5.7-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:11.5-alpine
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle
      - run:
        name: rspecを実行
        command: rspec