version: 2.1

orbs:
  ruby: circleci/ruby@1.0

jobs:
  build:
    working_directory: ~/circleci-demo-ruby-rails
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
        environment:
          PGHOST: 127.0.0.1
          RAILS_ENV: test
          BUNDLER_VERSION: 2.1.4
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password
    steps:
      - checkout
# bundle
      # Restore bundle cache
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run:
          name: bundle update
          command: gem install bundler:2.1.4
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: bundle install
          command: bundle check || bundle install
      # Store bundle cache
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
# yarn
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-
      - run:
          name: yarn
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
# db
      - run:
          name: setup database
          command: |
            cp -v config/database.ci.yml config/database.yml
      - run:
          name: DB を待機
      #     command: dockerize -wait tcp://localhost:5432 -timeout 1m
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 3m
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # # Build JavaScript files
      # - run: bundle exec bin/webpack