
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: el_training_development


test:
  <<: *default
  database: el_training_test

production:
  <<: *default
  database: el_training_production
  username: el_training
  password: <%= ENV['EL_TRAINING_DATABASE_PASSWORD'] %>
